/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCuisineRouteImport } from './routes/_app.cuisine'
import { Route as AppPlatsRouteImport } from './routes/_app.plats'
import { Route as ApiWsRouteImport } from './routes/api.ws'
import { Route as AppBarIndexRouteImport } from './routes/_app.bar.index'
import { Route as AppBarHistoriqueRouteImport } from './routes/_app.bar.historique'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCuisineRoute = AppCuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatsRoute = AppPlatsRouteImport.update({
  id: '/plats',
  path: '/plats',
  getParentRoute: () => AppRoute,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBarIndexRoute = AppBarIndexRouteImport.update({
  id: '/bar/',
  path: '/bar/',
  getParentRoute: () => AppRoute,
} as any)
const AppBarHistoriqueRoute = AppBarHistoriqueRouteImport.update({
  id: '/bar/historique',
  path: '/bar/historique',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connexion': typeof ConnexionRoute
  '/cuisine': typeof AppCuisineRoute
  '/plats': typeof AppPlatsRoute
  '/api/ws': typeof ApiWsRoute
  '/bar/historique': typeof AppBarHistoriqueRoute
  '/bar/': typeof AppBarIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/cuisine': typeof AppCuisineRoute
  '/plats': typeof AppPlatsRoute
  '/api/ws': typeof ApiWsRoute
  '/': typeof AppIndexRoute
  '/bar/historique': typeof AppBarHistoriqueRoute
  '/bar': typeof AppBarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_app/cuisine': typeof AppCuisineRoute
  '/_app/plats': typeof AppPlatsRoute
  '/api/ws': typeof ApiWsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bar/historique': typeof AppBarHistoriqueRoute
  '/_app/bar/': typeof AppBarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/cuisine'
    | '/plats'
    | '/api/ws'
    | '/bar/historique'
    | '/bar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/cuisine'
    | '/plats'
    | '/api/ws'
    | '/'
    | '/bar/historique'
    | '/bar'
  id:
    | '__root__'
    | '/_app'
    | '/connexion'
    | '/_app/cuisine'
    | '/_app/plats'
    | '/api/ws'
    | '/_app/'
    | '/_app/bar/historique'
    | '/_app/bar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ApiWsRoute: typeof ApiWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuisine': {
      id: '/_app/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof AppCuisineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plats': {
      id: '/_app/plats'
      path: '/plats'
      fullPath: '/plats'
      preLoaderRoute: typeof AppPlatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bar/': {
      id: '/_app/bar/'
      path: '/bar'
      fullPath: '/bar/'
      preLoaderRoute: typeof AppBarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/historique': {
      id: '/_app/bar/historique'
      path: '/bar/historique'
      fullPath: '/bar/historique'
      preLoaderRoute: typeof AppBarHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCuisineRoute: typeof AppCuisineRoute
  AppPlatsRoute: typeof AppPlatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBarHistoriqueRoute: typeof AppBarHistoriqueRoute
  AppBarIndexRoute: typeof AppBarIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCuisineRoute: AppCuisineRoute,
  AppPlatsRoute: AppPlatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBarHistoriqueRoute: AppBarHistoriqueRoute,
  AppBarIndexRoute: AppBarIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ApiWsRoute: ApiWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
